name: Android Message

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:


  send_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Create Changelog
        id: change-log
        uses: actions/github-script@v6.4.1
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        with:
          result-encoding: string
          script: |
            const commits = JSON.parse(process.env.COMMITS);
            var lines = "## What’s Changed\n\n";
            for (const commit of commits) {
              lines += "- " + commit.message + " (" + commit.id + ") @" + commit.author.username + "\n"
            }
            return lines
      - name: Checkout
        uses: actions/checkout@v2
      - name: POST Algo repo daily alarm to Slack
        shell: bash
        run: |
          # 현재 시간 정보 가져오기
          echo slack algo alarm
          NOW_DATE=$(date +%Y.%m.%d)
          NOW_MONTH=$(date +%0m)
          NOW_YEAR=$(date +%Y)
          # 이번 달에 해당하는 알고리즘 문제 풀이 폴더 찾고 푼 문제 개수 COUNT 변수에 저장
          # 알고리즘 문제 풀이 폴더들은 problems라는 디렉토리 안에 'YYYYmm'의 형식으로 만들어져야 인식됩니다.
          TARGET_FILE_NAME="${NOW_YEAR}${NOW_MONTH}"
          TARGET_FILE_PATH="problems/${TARGET_FILE_NAME}"
          COUNT=$(ls -al $TARGET_FILE_PATH | grep -E "^-.*\.py$|^-.*\.js" | wc -l | sed 's/ //g')
          SITUATION=""
          # 알고리즘 푼 문제 개수에 따른 응원(?)메시지 분기문
          if [ $COUNT -lt 10 ]
          then
          SITUATION="더 분발하세요!!!"
          elif [ $COUNT -ge 10 -a $COUNT -lt 20 ]
          then
          SITUATION="잘 하고 계시네요. 화이팅!!"
          elif [ $COUNT -ge 20 -a $COUNT -lt 30 ]
          then
          SITUATION="이번달 목표를 거의 다 달성하셨네요. 대단해요!!"
          else
          SITUATION="30문제 넘게 푸셨네요!!!! 대박대박 너무 짱짱맨입니다!!"
          fi
          DAILY_MESSAGE="알고리즘 문제 풀기 좋은 밤이네요!\n현재일($NOW_DATE)기준으로, *${NOW_YEAR}년 ${NOW_MONTH}월에 ${COUNT}문제* 푸셨어요\n한 달 목표는 *30문제* 입니다. ${SITUATION}"
          # 슬랙 채널로 메시지 요청
          curl -X POST --data-urlencode "payload={\"channel\":\"#알고_알리미\", \"username\":\"알고 알리미\", \"text\":\"${DAILY_MESSAGE}\", \"icon_emoji\": \":male-technologist:\"}" {% raw %}${{ secrets.SLACK_WEBHOOK_URL }}{% endraw %}
      - name: Notify slack message
        uses: 8398a7/action-slack@v3.15.1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              attachments: [{
                author_name: `${process.env.AS_AUTHOR}`,
                fallback: 'fallback',
                title: 'Deploy Result12',
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                fields: [{
                  "type": "mrkdwn",
                  title: "*About this build*:\nCommit header This is a multiple line commit message that might have some nice formatting?",
                  value: '*About this build*\nCommit have some nice formatting?\n\n',
                  short: true
                },
                {
                  title: 'Change Log',
                  value: 'Post Content :rocket:',
                  short: true
                },
                {
                  title: 'long title1',
                  value: `${process.env.AS_MESSAGE$}\n${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}\n\n'Post Content :rocket:'`,
                  short: false
                }],
                actions: [{
                  title: 'actions title1',
                  value: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                  short: false
                }]
              }],
            "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hello, Assistant to the Regional Manager Dwight! *Michael Scott* wants to know where you'd like to take the Paper Company investors to dinner tonight.\n\n *Please select a restaurant:*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Farmhouse Thai Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg",
                    "alt_text": "alt text for image"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Kin Khao*\n:star::star::star::star: 1638 reviews\n The sticky rice also goes wonderfully with the caramelized pork belly, which is absolutely melt-in-your-mouth and so soft."
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/korel-1YjNtFtJlMTaC26A/o.jpg",
                    "alt_text": "alt text for image"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{steps.change-log.outputs.result}}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/DawwNigKJ2ckPeDeDM7jAg/o.jpg",
                    "alt_text": "alt text for image"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Farmhouse",
                        "emoji": true
                      },
                      "value": "click_me_123"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Kin Khao",
                        "emoji": true
                      },
                      "value": "click_me_123",
                      "url": "https://google.com"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Ler Ros",
                        "emoji": true
                      },
                      "value": "click_me_123",
                      "url": "https://google.com"
                    }
                  ]
                }
              ]
            }
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket: ${{steps.change-log.outputs.result}}'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp