name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  post_slack:
    runs-on: [ self-hosted, android ]
    steps:
      - name: Notify slack success
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel: daily-build
          status: SUCCESS
          color: good
          text: ${{ github.event.head_commit.message }}
  send_slack:
    runs-on: [ self-hosted, android ]
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest  # selectable (default: repo,message)

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_TOKEN }} # required
      if: always() # Pick up events even if the job fails or is canceled.