name: Android Message

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:


  send_slack:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest,text  # selectable (default: repo,message)
          text: ${{ github.event.head_commit.message }}

        env:
          SLACK_BOT_TOKEN : ${{ secrets.SLACK_DEPLOY_TOKEN }} # required
  post_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack success
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_TOKEN }} # required
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          status: SUCCESS
          color: good
          text: ${{ github.event.head_commit.message }}