name: Android Message

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:


  send_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
          $lines = "## What’s Changed<br><br>"
          $commits = ${{ github.event.commits }}
          foreach ($commit in $commits) {
              $lines += $commit.message + " (" + $commit.id + ") @" + $commit.author.username + "<br>"
          }
      - name: Notify slack message
        uses: 8398a7/action-slack@v3.15.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

        with:
          status: custom
          fields: all
          custom_payload: |
            {
              attachments: [{
                author_name: `${process.env.AS_AUTHOR}`,
                fallback: 'fallback',
                title: 'Deploy Result1234',
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                fields: [{
                  type : 'mrkdwn'
                  title: '## What’s Changed',
                  value: '*About this build*\nCommit have some nice formatting?\n\n$$lines',
                  short: true
                },
                {
                  title: 'reverse',
                  value: 'gnirts esrever'.split('').reverse().join(''),
                  short: true
                },
                {
                  title: 'long title1',
                  value: `${process.env.AS_MESSAGE$}\n${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}\n\n'Post Content :rocket:'`,
                  short: false
                }],
                actions: [{
                  title: 'actions title1',
                  value: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                  short: false
                }]
              }]
            }
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp