name: Android Message

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:


  send_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack message
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

        with:
          status: custom
          fields: all
          custom_payload: |
            {
              attachments: [{
                author_name: `${process.env.AS_AUTHOR}`,
                fallback: 'fallback',
                title: 'Deploy Result',
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                fields: [{
                  "type": "mrkdwn",
                  title: "*About this build*:\nCommit header This is a multiple line commit message that might have some nice formatting?",
                  value: ${{ toJSON(github.event.head_commit.message) }},
                  short: true
                },
                {
                  title: 'reverse',
                  value: 'gnirts esrever'.split('').reverse().join(''),
                  short: true
                },
                {
                  title: 'long title1',
                  value: `${process.env.AS_MESSAGE$}\n${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                  short: false
                }],
                actions: [{
                  title: 'actions title1',
                  value: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                  short: false
                }]
              }]
            }
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'github_connection_test'
          slack-message: 'This message was sent through a proxy'
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]   
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}