name: Android Message

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:


  send_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack message
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

        with:
            status: custom
            fields: workflow,job,commit,repo,ref,author,took
            custom_payload: |
              {
                text: "Custom Field Check",
                attachments: [{
                  "author_name": "8398a7@action-slack", // json
                  fallback: 'fallback',
                  title: 'CI Result',
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                  fields: [{
                    title: 'lower case',
                    value: 'LOWER CASE CHECK'.toLowerCase(),
                    short: true
                  },
                  {
                    title: 'reverse',
                    value: 'gnirts esrever'.split('').reverse().join(''),
                    short: true
                  },
                  {
                    title: 'long title1',
                    value: 'long value1',
                    short: false
                  }],
                  actions: [{
                  }]
                }]
              }    

  post_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack success
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_TOKEN }} # required
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel: D04KCUGBDBK
          status: SUCCESS
          color: good