name: Android Message

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  send_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Create Changelog
        id: change-log
        uses: actions/github-script@v6.4.1
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        with:
          result-encoding: string
          script: |
            const commits = JSON.parse(process.env.COMMITS);
            var lines = "";
            for (const commit of commits) {
              if (commit.message.includes('VMTS-')) {
                lines += "- " + commit.message + " (" + commit.author.username + ")\n"
              }
            }
            return lines
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'name'
          SLACK_MSG_AUTHOR: '메세지 테스트'
          SLACK_LINK_NAMES: '@henry'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: '변경 내용 :fast_parrot:'
          SLACK_MESSAGE: '${{steps.change-log.outputs.result}}'
          SLACK_FOOTER: 'ㅇㅁㄴㅇ'
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_ICON: ':eyes:'